image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
       echo "creating assessment..." 
       && cd /workspace/assessment
       && shopt -s extglob
       && ls -adQ !(README.md) .[^.]* | xargs rm -Rf
       && git clone --bare https://github.com/deem-tests/gitpod-assessment-public /workspace/assessment/.git
       && git config core.bare false
       && git reset --hard HEAD 
       && echo "done."
    command: echo "ready!"

workspaceLocation: "assessment"    
checkoutLocation: "assessment"
